#!/usr/bin/env bash
# build-safe-batches.sh — pack Safe Transaction-Builder JSON files into Safe MultiSendCallOnly batches,
# compute each batch's safeTxHash (offline EIP-712, cross-checked against the Safe's on-chain
# getTransactionHash unless OFFLINE=1), and write decoded manifests + signer/executor commands.
#
# Usage: scripts/ops/SafeOnchainExec/build-safe-batches.sh [config.json]
#   env: RPC=<override rpc>  OFFLINE=1 (skip all RPC calls)
#
# Output (deterministic for a given config + inputs):
#   <outDir>/batch-NN-<name>.json      machine-readable batch (Safe tx fields, safeTxHash, inner calls)
#   <outDir>/batch-NN-<name>.decoded.md human-readable decode of every inner call
#   <outDir>/SUMMARY.md                 one table of all batches (nonce, hash, calls, files)
#   <outDir>/COMMANDS.md                cast commands for approveHash / execTransaction per batch
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
HERE=scripts/ops/SafeOnchainExec
# shellcheck source=lib.sh
source "$HERE/lib.sh"
load_config "${1:-$HERE/config/34443-0x6336.json}"
OFFLINE=${OFFLINE:-0}

mkdir -p "$OUT_DIR"
echo "Safe            : $SAFE (chain $CHAIN_ID)"
echo "MultiSendCallOnly: $MULTISEND"
echo "inputs          : $IN_DIR"
echo "outputs         : $OUT_DIR"

# --- sanity: on-chain nonce / threshold (informational unless OFFLINE) -------
ONCHAIN_NONCE=""; THRESHOLD=""; OWNERS=""
if [[ "$OFFLINE" != "1" ]]; then
  ONCHAIN_NONCE=$(cast call "$SAFE" 'nonce()(uint256)' --rpc-url "$RPC")
  THRESHOLD=$(cast call "$SAFE" 'getThreshold()(uint256)' --rpc-url "$RPC")
  OWNERS=$(cast call "$SAFE" 'getOwners()(address[])' --rpc-url "$RPC")
  MS_CODE=$(cast code "$MULTISEND" --rpc-url "$RPC")
  [[ "$MS_CODE" != "0x" ]] || { echo "ERROR: no code at MultiSendCallOnly $MULTISEND on chain $CHAIN_ID" >&2; exit 1; }
  echo "on-chain nonce  : $ONCHAIN_NONCE   threshold: $THRESHOLD"
  if [[ "$ONCHAIN_NONCE" != "$START_NONCE" ]]; then
    echo "WARNING: config startNonce=$START_NONCE but Safe nonce is $ONCHAIN_NONCE — hashes below are only valid if the Safe nonce is $START_NONCE when batch 1 executes." >&2
  fi
fi

# --- manifest check: every input file must be in MANIFEST.tsv with matching sha256 ----------
if [[ -f "$IN_DIR/MANIFEST.tsv" ]]; then
  while IFS=$'\t' read -r f repo commit path sha; do
    [[ "$f" == "file" || ! -f "$IN_DIR/$f" ]] && continue
    actual=$(shasum -a 256 "$IN_DIR/$f" | cut -d' ' -f1)
    [[ "$actual" == "$sha" ]] || { echo "ERROR: sha256 mismatch for $IN_DIR/$f (manifest $sha, actual $actual)" >&2; exit 1; }
  done < "$IN_DIR/MANIFEST.tsv"
  echo "manifest        : all input sha256 OK"
fi

ZERO=0x0000000000000000000000000000000000000000
NGROUPS=$(jq '.groups | length' "$CFG")
SUMMARY="$OUT_DIR/SUMMARY.md"; COMMANDS="$OUT_DIR/COMMANDS.md"
{
  echo "# Safe batches — $SAFE on chain $CHAIN_ID"
  echo
  echo "Generated by \`$HERE/build-safe-batches.sh $CFG\` (inputs: \`$IN_DIR\`). Safe nonce pinned at **$START_NONCE**; on-chain nonce at build time: **${ONCHAIN_NONCE:-n/a (OFFLINE)}**, threshold **${THRESHOLD:-n/a}**."
  echo
  echo "All Safe txs: \`to=$MULTISEND (MultiSendCallOnly)\`, \`value=0\`, \`operation=1 (DELEGATECALL)\`, \`safeTxGas=0\`, \`baseGas=0\`, \`gasPrice=0\`, \`gasToken=0x0\`, \`refundReceiver=0x0\`."
  echo
  echo "| # | nonce | batch | inner calls | source files | calldata bytes | safeTxHash |"
  echo "|---|---|---|---|---|---|---|"
} > "$SUMMARY"
{
  echo "# Signer / executor commands — $SAFE on chain $CHAIN_ID"
  echo
  echo "Replace \`<SIGNER-OPTS>\` with your key option, e.g. \`--ledger\`, \`--trezor\`, \`--account <name>\` or \`--interactive\`. RPC: \`$RPC\`."
  echo
} > "$COMMANDS"

for (( gi=0; gi<NGROUPS; gi++ )); do
  name=$(jq -r ".groups[$gi].name" "$CFG"); desc=$(jq -r ".groups[$gi].description" "$CFG")
  nonce=$(( START_NONCE + gi )); num=$(printf '%02d' $((gi+1)))
  echo; echo "== batch $num ($name) nonce=$nonce"
  packed=""; calls_json="[]"; idx=0; nfiles=0
  decoded_md="$OUT_DIR/batch-$num-$name.decoded.md"
  {
    echo "# Batch $num — $name (Safe nonce $nonce)"
    echo; echo "$desc"; echo
    echo "| # | source file | # in file | target | function | decoded |"; echo "|---|---|---|---|---|---|"
  } > "$decoded_md"
  for f in $(jq -r ".groups[$gi].files[]" "$CFG"); do
    fp="$IN_DIR/$f"; [[ -f "$fp" ]] || { echo "ERROR: missing input $fp" >&2; exit 1; }
    fchain=$(jq -r '.chainId' "$fp"); [[ "$fchain" == "$CHAIN_ID" ]] || { echo "ERROR: $f has chainId $fchain, expected $CHAIN_ID" >&2; exit 1; }
    nfiles=$((nfiles+1)); ntx=$(jq '.transactions|length' "$fp")
    for (( ti=0; ti<ntx; ti++ )); do
      to=$(jq -r ".transactions[$ti].to" "$fp"); data=$(jq -r ".transactions[$ti].data" "$fp")
      value=$(jq -r ".transactions[$ti].value // \"0\"" "$fp"); op=$(jq -r ".transactions[$ti].operation // \"0\"" "$fp")
      [[ "$op" == "0" ]] || { echo "ERROR: $f tx $ti has operation=$op; MultiSendCallOnly only allows CALL(0)" >&2; exit 1; }
      [[ "$data" =~ ^0x([0-9a-fA-F]{2})*$ ]] || { echo "ERROR: $f tx $ti has invalid hex data" >&2; exit 1; }
      packed="${packed}$(pack_call 0 "$to" "$value" "$data")"
      dec=$(decode_call "$to" "$data"); fn=${dec%% |*}; args=${dec#*| }
      printf '| %d | %s | %d | %s | %s | %s |\n' "$idx" "$f" "$ti" "$(label "$to")" "$fn" "$args" >> "$decoded_md"
      calls_json=$(jq -c --arg f "$f" --argjson ti "$ti" --arg to "$to" --arg v "$value" --arg d "$data" --arg fn "$fn" --arg args "$args" \
        '. + [{file:$f, indexInFile:$ti, to:$to, value:$v, data:$d, function:$fn, decoded:$args}]' <<< "$calls_json")
      idx=$((idx+1))
    done
  done
  msdata=$(multisend_calldata "$packed")
  hash_off=$(safe_tx_hash_offline "$MULTISEND" 0 "$msdata" 1 0 0 0 "$ZERO" "$ZERO" "$nonce")
  hash_on=""
  if [[ "$OFFLINE" != "1" ]]; then
    hash_on=$(safe_tx_hash_onchain "$MULTISEND" 0 "$msdata" 1 0 0 0 "$ZERO" "$ZERO" "$nonce")
    [[ "$hash_on" == "$hash_off" ]] || { echo "ERROR: offline hash $hash_off != on-chain getTransactionHash $hash_on" >&2; exit 1; }
    echo "   safeTxHash (offline == on-chain getTransactionHash): $hash_off"
  else
    echo "   safeTxHash (offline): $hash_off"
  fi
  bytes=$(( (${#msdata} - 2) / 2 ))
  echo "   inner calls: $idx  files: $nfiles  multiSend calldata: $bytes bytes"
  jq -n --arg name "$name" --arg desc "$desc" --argjson nonce "$nonce" --arg safe "$SAFE" --argjson chainId "$CHAIN_ID" \
        --arg to "$MULTISEND" --arg data "$msdata" --arg hash "$hash_off" --arg hashOn "${hash_on:-}" --arg ds "$(safe_domain_separator_offline)" \
        --argjson calls "$calls_json" --arg zero "$ZERO" '{
          batch:$name, description:$desc, safe:$safe, chainId:$chainId, nonce:$nonce,
          safeTx:{to:$to, value:"0", data:$data, operation:1, safeTxGas:"0", baseGas:"0", gasPrice:"0", gasToken:$zero, refundReceiver:$zero, nonce:$nonce},
          domainSeparator:$ds, safeTxHash:$hash, safeTxHashOnchain:(if $hashOn=="" then null else $hashOn end),
          innerCallCount:($calls|length), calls:$calls }' > "$OUT_DIR/batch-$num-$name.json"
  {
    echo; echo "**safeTxHash:** \`$hash_off\`  "; echo "**multiSend calldata:** $bytes bytes, keccak256 = \`$(cast keccak "$msdata")\`  "
    echo "**Safe tx:** to=\`$MULTISEND\` value=0 operation=1(DELEGATECALL) nonce=$nonce safeTxGas=0 baseGas=0 gasPrice=0"
  } >> "$decoded_md"
  files_list=$(jq -r ".groups[$gi].files | join(\"<br>\")" "$CFG")
  printf '| %s | %d | %s | %d | %d | %d | `%s` |\n' "$num" "$nonce" "$name" "$idx" "$nfiles" "$bytes" "$hash_off" >> "$SUMMARY"
  {
    echo "## Batch $num — $name (nonce $nonce)"; echo
    echo "safeTxHash: \`$hash_off\`"; echo
    echo "**Approve (each signer, any order, any time before execution):**"; echo
    echo '```bash'
    echo "cast send $SAFE 'approveHash(bytes32)' $hash_off --rpc-url $RPC <SIGNER-OPTS>"
    echo '```'
    echo "Check an approval landed: \`cast call $SAFE 'approvedHashes(address,bytes32)(uint256)' <OWNER> $hash_off --rpc-url $RPC\` → \`1\`."; echo
    echo "**Execute (batches MUST go in nonce order). Cheapest: threshold-1 owners approve, another OWNER executes (msg.sender counts as an approval):**"; echo
    echo '```bash'
    echo "$HERE/exec-safe-batch.sh $CFG $num --approvers <OWNER_A>,<OWNER_B> --sender <OWNER_C>                      # dry run"
    echo "$HERE/exec-safe-batch.sh $CFG $num --approvers <OWNER_A>,<OWNER_B> --sender <OWNER_C> --send <SIGNER-OPTS> # broadcast from OWNER_C"
    echo '```'
    echo "(If ≥ threshold owners approved, anyone can execute: pass all approvers and any --sender. Without \`--send\` the script only verifies approvals, eth_call-simulates and prints the raw execTransaction calldata.)"; echo
  } >> "$COMMANDS"
done
{
  echo; echo "Inner-call decodes: \`batch-NN-<name>.decoded.md\`. Machine-readable: \`batch-NN-<name>.json\`. Commands: \`COMMANDS.md\`."
  [[ -n "$OWNERS" ]] && { echo; echo "Safe owners at build time: \`$OWNERS\`"; }
} >> "$SUMMARY"
echo; echo "Wrote $SUMMARY, $COMMANDS and per-batch files."
