// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {VmSafe} from "forge-std/Vm.sol";
import {Script} from "forge-std/Script.sol";
import {console2 as console} from "forge-std/console2.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";

struct SerializedTx {
    string name;
    address to;
    uint256 value;
    bytes data;
}

contract SafeTxUtil is Script {
    using stdJson for string;

    function writeTxs(SerializedTx[] memory txs, string memory path) public {
        // Escape hatch for hosts where the JSON cheatcodes are unavailable: builds the same
        // document with plain string concatenation and logs it for extract-console-safe-json.py
        // instead of calling vm.serialize*/vm.writeJson/vm.ffi. Verified to produce output
        // semantically identical to the cheatcode path (see extract-console-safe-json.py).
        //
        // NOTE: this does NOT make `forge --zksync` work. That reverts for a separate reason
        // still undiagnosed -- console.log and string.concat were both proven fine under
        // --zksync, and execution never reaches this function. ZKsync Era (324) and Abstract
        // (2741) are generated by generate-unforkable-batches.py over plain eth_calls instead.
        if (vm.envOr("SAFE_TX_CONSOLE_JSON", false)) {
            _logTxsJson(txs, path);
            return;
        }

        string memory json = "json";
        // Default values
        vm.serializeString(json, "version", "1.0");
        vm.serializeUint(json, "chainId", block.chainid);
        vm.serializeUint(json, "createdAt", block.timestamp * 1000);

        string memory serializedTxs = "[";
        for (uint i = 0; i < txs.length; i++) {
            if (i != 0) {
                serializedTxs = string.concat(serializedTxs, ",");
            }

            string memory transaction = "tx";
            vm.serializeAddress(transaction, "to", txs[i].to);
            vm.serializeString(
                transaction,
                "value",
                Strings.toString(txs[i].value)
            );
            vm.serializeString(transaction, "operation", "0");
            string memory serializedTx = vm.serializeBytes(
                transaction,
                "data",
                txs[i].data
            );

            serializedTxs = string.concat(serializedTxs, serializedTx);
        }
        serializedTxs = string.concat(serializedTxs, "]");

        string memory meta = "meta";
        vm.serializeString(meta, "name", "Transactions Batch");
        string memory serializedMeta = vm.serializeString(
            meta,
            "description",
            ""
        );

        vm.serializeString(json, "transactions", serializedTxs);
        string memory finalJson = vm.serializeString(
            json,
            "meta",
            serializedMeta
        );

        vm.writeJson({json: finalJson, path: path});

        string[] memory commands = new string[](4);
        // re-used commands to find-replace
        commands[0] = "sed";
        commands[1] = "-i";
        commands[3] = path;

        // Remove all backslashes
        commands[2] = "s/\\\\//g";
        vm.ffi(commands);

        // Replace `"[` with `[`]
        commands[2] = 's/\\"\\[/\\[/g';
        vm.ffi(commands);

        // Replace `]"` with `]`
        commands[2] = 's/\\]\\"/\\]/g';
        vm.ffi(commands);
    }

    /// @dev Emits the same Safe batch document as the cheatcode path, built purely with string
    ///      concatenation so it survives `forge --zksync`. Only console.log is used; vm.toString
    ///      is avoided too, since it is a cheatcode and the point here is to depend on none of
    ///      them. Field types match the cheatcode output exactly (chainId/createdAt numeric,
    ///      version/value/operation strings) so both paths produce interchangeable files.
    function _logTxsJson(SerializedTx[] memory txs, string memory path) internal view {
        string memory body = string.concat(
            '{"version":"1.0","chainId":',
            Strings.toString(block.chainid),
            ',"createdAt":',
            Strings.toString(block.timestamp * 1000),
            ',"meta":{"name":"Transactions Batch","description":""},"transactions":['
        );

        for (uint256 i = 0; i < txs.length; i++) {
            if (i != 0) {
                body = string.concat(body, ",");
            }
            body = string.concat(
                body,
                '{"to":"',
                Strings.toHexString(uint160(txs[i].to), 20),
                '","value":"',
                Strings.toString(txs[i].value),
                '","operation":"0","data":"',
                _bytesToHex(txs[i].data),
                '"}'
            );
        }

        body = string.concat(body, "]}");

        console.log(string.concat("SAFE_TX_JSON_BEGIN ", path));
        console.log(body);
        console.log("SAFE_TX_JSON_END");
    }

    function _bytesToHex(bytes memory _data) internal pure returns (string memory) {
        bytes memory alphabet = "0123456789abcdef";
        bytes memory out = new bytes(2 + _data.length * 2);
        out[0] = "0";
        out[1] = "x";
        for (uint256 i = 0; i < _data.length; i++) {
            out[2 + i * 2] = alphabet[uint8(_data[i] >> 4)];
            out[3 + i * 2] = alphabet[uint8(_data[i] & 0x0f)];
        }
        return string(out);
    }
}